# Generated by Django 4.0.4 on 2023-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='version',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('REALIZED', 'Already completed'), ('STARTED BUT NOT REALIZED YET', 'Started, but not finished yet'), ('NOT STARTED YET', 'Not started yet')], default='NOT STARTED YET', max_length=32),
        ),
    ]
