# Generated by Django 4.0.4 on 2023-02-28 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_version_ticket_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='model',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='month',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='year',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 16, 46, 55, 198022)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=32),
        ),
    ]
