# Generated by Django 4.0.4 on 2023-02-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_model_category_rename_model_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 16, 48, 47, 548692)),
        ),
    ]
