# Generated by Django 4.0.4 on 2023-03-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_date_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 18, 41, 58, 182626)),
        ),
    ]
